version: '3'

networks:
  # enable connection with Traefik
  traefik:
    external: true
  # network for the app
  apps-network:

services:
  nginx:
    container_name: "site-cloudsecure-web"
    image: nginx:stable-alpine
    #image: jvnetobr/nginx:1.1
    depends_on:
      - php-fpm
    restart: always
    env_file:
      #- ./env/app.env
      - ./.env
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # app files
      - ./app:/var/www/html
      #- ./app/wp-content:/var/www/html/wp-content
      # - ./app/wp-config.php:/var/www/html/wp-config.php
    networks:
      - traefik
      - apps-network
    ports:
      - "8000:80"
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Get the routes from http
      #- "traefik.http.routers.site-exemplo.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.site-cloudsecure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.site-cloudsecure.entrypoints=web"
      # Redirect these routes to https
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.site-cloudsecure.middlewares=redirect-to-https@docker"
      # Get the routes from https
      #- "traefik.http.routers.site-exemplo-secured.rule=Host(`${DOMAIN}`) && PathPrefix(`/DOMAINPATH`)"
      - "traefik.http.routers.site-cloudsecure-secured.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.site-cloudsecure-secured.entrypoints=web-secure"
      # Apply autentificiation with http challenge
      - "traefik.http.routers.site-cloudsecure-secured.tls=true"
      - "traefik.http.routers.site-cloudsecure-secured.tls.certresolver=myhttpchallenge"

  php-fpm:
    container_name: "site-cloudsecure-php"
    #image: php:fpm-alpine
    image: jvnetobr/php-fpm:1.0
    volumes:
      - ./app:/var/www/html
      #- ./app/wp-content:/var/www/html/wp-content
      #- ./app/wp-config.php:/var/www/html/wp-config.php
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - apps-network
    #ports:
      #- "9000:9000"
    depends_on:
      - db

  db:
    container_name: "site-cloudsecure-db"
    #image: mysql:5.7
    image: mysql:8.0
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - ./db:/var/lib/mysql
      #- ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - apps-network